listener 8883 0.0.0.0

cafile D:\IoT-Sensor-System\certs\ca.crt
certfile D:\IoT-Sensor-System\certs\server.crt
keyfile D:\IoT-Sensor-System\certs\server.key

listener_allow_anonymous false
password_file C:\Program Files\mosquitto\passwd

socket_domain ipv4